version = 0.1

[default.deploy.parameters]
stack_name = "supermarket-iot-hd"
resolve_s3 = true
s3_prefix = "supermarket-iot-hd"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "InventoryTableName=\"Inventory\" OrdersTableName=\"Orders\""
image_repositories = []
